### ISSUE TITLE
How to setup?

### ISSUE THREAD

**Issue by zeroby0** [carlfriess/DigitalOceanVPNSetup#1]
Hey, Thanks for the setup. I created a droplet using that, and got a config file, what do I do next? I'm on  a mac if that helps.

**Comment by carlfriess** [comment]
On a mac you can simple open the .networkConnect file. System Preferences should open and add the configuration for you. Alternatively, you can add the configuration yourself using the information provided at the end of the setup. [Here](http://www.watchguard.com/help/docs/wsm/xtm_11/en-us/content/en-us/mvpn/l2tp/l2tp_vpn_client_macosx_c.html) is a guide on how to do that. Hope that helps! 😊
