### ISSUE TITLE
Doesn't seem to be Team Aware

### ISSUE THREAD

**Issue by nelsonjchen** [carlfriess/DigitalOceanVPNSetup#10]
I authorized it to use my DO account and granted it access to my account and to a team. This doesn't offer to choose a team/account to install to and notably it failed during setup.

**Comment by carlfriess** [comment]
Should be working again now. Unfortunately, it isn't possible to make the tool team aware, as this isn't supported by the DigitalOcean API (see [here](https://www.digitalocean.com/community/questions/it-is-possible-to-create-a-droplet-in-a-specific-team-by-the-api)).
