### ISSUE TITLE
An error occurred! Please refresh the page!

### ISSUE THREAD

**Issue by sembozdemir** [carlfriess/DigitalOceanVPNSetup#11]
I got this error while script is trying to create a droplet.

**Comment by yadude87** [comment]
Has already been reported here

**Comment by hwdsl2** [comment]
The issue could be that the Ubuntu 14.04 image is no longer available on DigitalOcean. Related code: [1].

@carlfriess Could you please update the image to e.g. Ubuntu 20.04?

[1] https://github.com/carlfriess/DigitalOceanVPNSetup/blob/gh-pages/index.html#L396

**Comment by carlfriess** [comment]
Fixed in 7dba603dd73faabf4fb06a041f18e43fd1052450. Thanks for reporting!
