### ISSUE TITLE
config.networkConnect contains incorrect password

### ISSUE THREAD

**Issue by josephfusco** [carlfriess/DigitalOceanVPNSetup#2]
After a few tries of failing to connect, I realized that the password within `config.networkConnect` had more characters than the actual password.

**Comment by carlfriess** [comment]
Thanks! I‘m aware of the issue. Unfortunately, it’s not publicly known how Apple encrypts passwords in .networkConnect files. The code ind the VPN setup is something I hacked together using tips from the internet. It did work, however something changed in recent versions of macOS. Input is welcome.

**Comment by tsal** [comment]
@carlfriess I would suggest removing download button for `config.networkConnect`; it generates some confusion and comments in places not just on github. it took some digging to find out I just needed to rerun the script manually on the server to get the correct credentials and login.

**Comment by tsal** [comment]
(and I sympathize; I've run into similar issues with Apple when it comes to documentation around their keychains)

**Comment by carlfriess** [comment]
I've removed the password from the configuration file in af2225e5a6f9d41bff065510cd9a54d8a49fd9a0.
