### ISSUE TITLE
any ubuntu based client to connect?

### ISSUE THREAD

**Issue by helxsz** [carlfriess/DigitalOceanVPNSetup#3]
I have built the VPN successfully on the digitalocean, my MAC and iphone works in the VPN. However i just wonder is there any ubuntu based client can connect to the VPN as well, do you have any idea?

**Comment by carlfriess** [comment]
You can use any L2TP (IPSec) VPN client. This functionality isn't built in to Ubuntu anymore, but it can easily be installed. Here is a cool guide: https://www.cactusvpn.com/tutorials/how-to-set-up-l2tpipsec-vpn-on-ubuntu/

Hope that helps!
