### ISSUE TITLE
Setup issue for poor w*ndows users

### ISSUE THREAD

**Issue by feldrim** [carlfriess/DigitalOceanVPNSetup#4]
I'm a w*ndows user for work related issues and created an droplet on DO thanks to you. Since yesterday, I managed to do all things I could'do: create the droplet, update tools, setup a VNC for management next to SSH etc.

Everything seems ok on the server side but I couldn't manage to connect to the VPN from my W*ndows 10 PC and Android phone. I tried to check if ipsec and other services are working and it seems to be running healthily. Since there seems to be no problem around, I couldn't connect to/through the VPN.

I checked the [ipsec repo](https://github.com/hwdsl2/setup-ipsec-vpn) and tried possible solutions for W*ndows troubleshooting: still no connection. I'm pretty sure it's a simple thing for linux users to troubleshoot these things but for me, it's like I'm working on a Chinese console app while using Latin keyboard.

**Comment by carlfriess** [comment]
Can you give more specifics about the problem? What exactly isn't working? What steps did you take?

**Comment by feldrim** [comment]
- I've logged in on http://dovpn.carlfriess.com/
- I ran the script and got my credentials.
- I thought  I might need a GUI. I found this [article](https://www.digitalocean.com/community/tutorials/how-to-setup-vnc-for-ubuntu-12) about setting up a VNC on Ubuntu and tried to do the steps but turned out to be for Ubuntu 12.
- Then I followed this [article](https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-vnc-on-ubuntu-14-04) and set up VNC. It worked.
- I connected using Putty. I could see services are up.
- On my PC and Android, I used the credentials I got through the script. I couldn't reach it.
- I checked the IPSec repo and looked at the [Windows client setup](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#windows). Followed the steps, it didn't work.
- I looket through the [Troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#troubleshooting) section and tried all the steps mentioned. It didn't work.
- Checked all the services but I never succeeded to connect to my VPN.

**Comment by carlfriess** [comment]
The script is designed to setup machines for VPN only. If you run other services you're on your own. Try running the setup without touching anything afterwards. You should be able to connect then.

I'll close this issue for now. If you have any other issues relating to this project please feel free to reopen it. :)

**Comment by feldrim** [comment]
I've destroyed the droplet and recreated a new one. This is the same error I get before.
It says "Cannot connect to Digitalocean".

![do](https://user-images.githubusercontent.com/15658960/31406502-42ae2c5a-ae0a-11e7-8852-ae8cfe099c34.PNG)

**Comment by carlfriess** [comment]
If you can connect on a different device, then there most likely isn’t an issue with the setup. Make sure your Windows machine is configured correctly. Maybe have a look at this: https://www.cactusvpn.com/tutorials/how-to-set-up-l2tp-vpn-on-windows-10/
