### ISSUE TITLE
authentication failed

### ISSUE THREAD

**Issue by helxsz** [carlfriess/DigitalOceanVPNSetup#5]
i have built the digitalocean VPN server successfully, however I can't connect to VPN from my mac.

here is the VPN information and error,
![screen shot 2017-10-11 at 13 51 36](https://user-images.githubusercontent.com/669670/31441925-94aa4e44-ae8c-11e7-83cd-834a428a2b14.png)

when I opened the config.networkConnect, the shared secret is 					D8MFe77bsdLg+EhF4Bxgh/S+oNT8aAfM instead of IPspec key shown above, what is wrong ? 

how could i fix it ?

**Comment by iosdevsx** [comment]
same issue, any idea?

**Comment by vitalys** [comment]
@helxsz Just use credentials from page (they are correct)

**Comment by carlfriess** [comment]
Fixed. See #2
